### ISSUE TITLE
Watch sermons on native mobile app

### ISSUE THREAD

**Issue by bradmsmith** [CompassHB/mobile#1]
Determine approach
* Framework like Ionic
* Wrapper of existing web page

The goal of this is to view sermons. No other features.

**Comment by ewinslow** [comment]
Acknowledging that the initial use case is quite simple, I could see a compass app evolving into much more than viewing sermons over time.

Short term, though I would think we should do whatever allows us to get something going asap, yea?

**Comment by bradmsmith** [comment]
![how-to-build-a-minimum-viable-product](https://cloud.githubusercontent.com/assets/4544726/6424928/40d9d688-bec3-11e4-860d-2a1da10c1878.jpg)

**Comment by ewinslow** [comment]
Haha, that's awesome.
