### ISSUE TITLE
Tab 4 (Events): Create List of Events

### ISSUE THREAD

**Issue by bradmsmith** [CompassHB/mobile#12]
On the Events tab display a scroll list of all upcoming events using https://api.compasshb.com/wp-json/wp/v2/tribe_events The scroll list should look like the lists on the other tabs in the app with a title and thumbnail image.

Allow users to click on an event to show the event details and image.

**Comment by bradmsmith** [comment]
Pull from https://api.compasshb.com/wp-json/wp/v2/tribe_events or Falcor endpoint

**Comment by bradmsmith** [comment]
bhupesharora

**Comment by bhupesharora** [comment]
Above link for list of events , image url link is not there in api 

so what i have to do either set static image or you are going to change the api

**Comment by bradmsmith** [comment]
Try https://api.compasshb.com/wp-json/wp/v2/tribe_events?_embed
The thumbnails are under wp:featured media. If an event does not have a thumbnail set a default static image

**Comment by bhupesharora** [comment]
Commit is done for this issue after review close this issue
