### ISSUE TITLE
Tab 2 (Teaching): Remove Comments on Individual View

### ISSUE THREAD

**Issue by bradmsmith** [CompassHB/mobile#16]
Comments should only show on the Scripture/text reading view. Keep the video/sermon content. Remove the "Disqus" comments that load under the content on the Sermons tab.

<img width="291" alt="screen shot 2017-02-21 at 3 31 40 pm" src="https://cloud.githubusercontent.com/assets/4544726/23190142/163b80d4-f84b-11e6-9f48-32747e670f9e.png">

**Comment by bradmsmith** [comment]
asterism1985

**Comment by Asterism1985** [comment]
Hi Brad,

If you want to remove the comments on individual view page, you have to change it in "https://compasshb.disqus.com/embed.js"
But I didn't have it now.
Can you change it in your side?

Regards

**Comment by bradmsmith** [comment]
There is a function called renderDisqusComments() that needs to be disabled for this tab.
mobile/src/Views/ItemDetailView.js
