### ISSUE TITLE
Tab 3 (Training): CSS Styles on Individual View

### ISSUE THREAD

**Issue by bradmsmith** [CompassHB/mobile#18]
Apply these Styles to the Scripture of the Day text on the mobile app:

http://static.esvmedia.org/legacy/css/text.css

<img width="375" alt="screen shot 2017-02-21 at 4 42 29 pm" src="https://cloud.githubusercontent.com/assets/4544726/23191846/ce2045d2-f854-11e6-938d-0178b2ba8de5.png">

HTML content is from: https://api.compasshb.com/reading/wp-json/wp/v2/posts?_embed

**Comment by bradmsmith** [comment]
bhupesharora

**Comment by bhupesharora** [comment]
Commit is done for this issue after review close this issue
